file_format: "1"
id: ccaikb
name: ccaikb
type: shield
url: https://github.com/josefadamcik/SofleKeyboard
requires: [pro_micro]
features:
  - keys
  - display
  - studio
siblings:
  - ccaikb_left
  - ccaikb_right
  - ccaikb_left_peripheral
  - ccaikb_dongle_xiao
  - ccaikb_dongle_pro_micro
